---
- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: restart multipathd
  ansible.builtin.systemd:
    name: multipathd
    state: restarted
